// config for the app
import { SkillGroup } from "../types";

export { SKILL_GROUPS, CV_TEXT, NAME, PROFESSIONAL_TITLE };

const NAME = "Romilly Eveleigh";
const PROFESSIONAL_TITLE = "AI Engineer & Senior Full-Stack Developer";

const SKILL_GROUPS: SkillGroup[] = [
  {
    name: "AI & Machine Learning",
    skills: [
      "AI Agents",
      "AI-Powered Search",
      "LLM Integration",
      "Prompt Engineering",
      "Embeddings & Vector Search",
      "Text-to-Speech",
      "Google Gemini",
      "Anthropic / Claude",
    ],
  },
  {
    name: "Frontend",
    skills: ["React", "Next.js", "TypeScript", "JavaScript", "Tailwind", "Redux Toolkit"],
  },
  {
    name: "Backend & Cloud",
    skills: ["Node.js", "NestJS", "GraphQL", "PostgreSQL", "AWS", "GCP", "Azure", "Docker", "CI/CD"],
  },
  {
    name: "Engineering & Delivery",
    skills: [
      "Software Architecture",
      "Technical Strategy",
      "Agile / Scrum",
      "Code Review",
      "Mentoring",
      "Team Leadership",
    ],
  },
];

const CV_TEXT = `
Romilly Eveleigh
AI Engineer · Senior Full-Stack · React · TypeScript · Node
London, UK · +44 7939 308 958 · romillysemail@gmail.com
linkedin.com/in/romilly-eveleigh-96699138 · github.com/romillyeveleigh

Professional Summary
AI engineer and senior full-stack developer with 8+ years shipping production software. I build AI products
end-to-end — from AI assistants and smart search to apps used by hundreds of thousands of people. Founder of
Situ.art, an AI product now live on the App Store. Earlier I led engineering teams of up to 12 at organisations
including Sainsbury's, BT/EE, and Framestore.
Available for senior AI & engineering roles · hybrid within UTC−3 to UTC+5 · UK work-eligible.

Selected AI Work
• AI coding agent — Built an internal AI assistant that completes engineering work, and used it to ship several
  hundred features to production. (Apolitical)
• Smart image search — Built AI-powered search that finds images by what they mean, not just keywords, across
  thousands of images. (Apolitical)
• AI audio narration — Built a tool that turns written lessons into natural, podcast-style audio, generated by AI
  on demand. (Apolitical)
• Interactive AI learning — Designed and shipped AI learning features now used by 20,000+ people. (Apolitical)
• AI product (founder) — Built Situ.art, an AI app that shows artworks in real rooms for galleries and collectors;
  live on the App Store.

Core Skills
AI & Machine Learning: AI Agents, AI-Powered Search, LLM Integration, Prompt Engineering, Embeddings & Vector
Search, Text-to-Speech, Google Gemini, Anthropic / Claude
Frontend: React, Next.js, TypeScript, JavaScript, Tailwind, Redux Toolkit, HTML/CSS
Backend & Cloud: Node.js, NestJS, GraphQL, PostgreSQL, AWS, GCP, Azure, Docker, CI/CD
Engineering & Delivery: Software Architecture, Technical Strategy, Agile / Scrum, Code Review, Mentoring, Team
Leadership

Professional Experience

Senior Full Stack Software Engineer, Apolitical · London, UK
Nov 2024 - Present
Driving technical direction and architecture on an e-learning and professional networking platform serving
~500,000 public servants globally, contributing to roadmap planning across the engineering team.
Redesigned the server-side rendering architecture, cutting page load times from 5s to under 0.5s — a 10×
improvement at scale.
Technologies: Next.js, TypeScript, GCP, GraphQL, NestJS, TanStack, Radix, PostgreSQL, Claude Code

Technical Consultant, Queens Lane Consultants · London, UK
Jul 2025 - Present
Engaged as sole technical consultant to a London-based accounting and tax consultancy, providing engineering
leadership across a team of 4 full-time developers.
Established cross-team collaboration standards — ticket-based project management, structured bug documentation,
and AI-assisted development with Claude Code.
Delivered a full platform — customer portal, consultant portal, and multilingual marketing site — for
Forschungszulage Beratungs Gruppe (FBG), a German R&D tax consultancy, end-to-end.
Technologies: Next.js, TypeScript, Tailwind, Supabase, i18n, Vercel

Lead Front End Developer, Framestore · London, UK
Jul 2022 - Oct 2024
Took a SaaS smart signage platform from early prototype to global production, deployed at Goldman Sachs and
London Stock Exchange — leading a team of 4 senior engineers.
Owned the full engineering lifecycle: architecture, coding standards, design reviews, and delivery against a
complex product roadmap, plus hiring and onboarding.
Collaborated directly with stakeholders to scope product requirements across creative, commercial, and technical
needs.
Technologies: React, TypeScript, Redux Toolkit, AWS (Lambda, DynamoDB, S3), Material UI, Cypress

Senior Full Stack Developer & Squad Lead, NTT DATA (BT / EE) · London, UK
Sep 2021 - Jul 2022
Delivered a high-traffic customer account management portal for the UK's largest telecommunications provider —
leading a squad of front-end and QA engineers within a 50+ person programme.
Translated complex enterprise requirements into deliverable, well-tested features across cross-functional teams.
Introduced Storybook-driven component development, improving design–engineering collaboration and delivery
velocity.
Technologies: Next.js, React, TypeScript, MSAL / Azure AD, API Management, Storybook

Senior Full Stack Developer & Team Lead, Nectar360 (Sainsbury's) · London, UK
Jul 2020 - Aug 2021
Architected data visualisation tools enabling the sales team to pitch and sell in-store advertising — processing
billions of customer transaction records to surface actionable insights.
Delivered internal tooling for the Nectar loyalty scheme, leading a cross-functional team of 12 developers, data
scientists, and DevOps engineers, with code reviews and mentoring across disciplines.
Acted as the primary interface between engineering and senior stakeholders, translating business requirements
into technical specifications.
Technologies: React, TypeScript, Node.js, DynamoDB, AWS, Docker, MariaDB, Azure, Storybook

Freelance Web Developer, Ovcharenko Ltd · Ho Chi Minh City, Vietnam
Dec 2015 - Jul 2020
Designed and delivered responsive e-commerce platforms and digital content services for a range of commercial
clients.
Technologies: Node.js, JavaScript, Express, MongoDB, PostgreSQL, HTML/CSS

Project Manager, Regina London · London, UK
2010 - 2015
Project manager for a contemporary art gallery and its international exhibitions programme (art fairs in Berlin,
Basel, New York, and Moscow), leading a team of 10+ across curatorial, sales, and operations with full P&L
ownership.
Set up the gallery's London office and digital infrastructure — databases, digital marketing, archive, and client
presentation materials.

Earlier experience in web development and project management (2004–2015) available on request.

Founder & Side Projects

Situ.art
2026 - Present
situ.art
Founded and built an AI platform that lets artists, galleries, and auction houses see artwork in real spaces
through photorealistic mock-ups, plus an API for galleries to produce images at scale. Uses AI image generation,
carefully tuned for professional-quality results across several AI models. Sole founder and developer; now live on
the App Store.
Stack: Next.js, TypeScript, Tailwind, Google Gemini, Supabase, Stripe

What Visa?
2020 - 2023
whatvisa.com
Co-founded and built a legal-tech SaaS product helping users assess UK Skilled Worker visa eligibility. Accredited
by the Office of the Immigration Services Commissioner and selected for the LawtechUK sandbox programme backed by
the UK Ministry of Justice.
Stack: Next.js, TypeScript, Firebase

Education
BA History of Art
1999 - 2002
Courtauld Institute, University of London`;
